# Generated by Django 5.2.8 on 2025-11-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemain',
            name='position',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pemain',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
